global:
  postgresql:
    auth:
      database: "users_db"

postgresql:
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: "standard"
      accessModes:
        - ReadWriteOnce
      mountPath: /data/postgresql
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
    podSecurityContext:
      enabled: true
      fsGroup: 1001
      runAsUser: 1001
      runAsNonRoot: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

service:
  type: ClusterIP
  port: 5432

volumePermissions:
  enabled: true