apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dosa-chart.fullname" $ }}-secrets
type: Opaque
data:
  database.appUser.username: {{ .Values.secret.database.appUser.username | b64enc | quote }}
  database.sa.name: {{ .Values.secret.database.sa.name | b64enc | quote }}